### ISSUE TITLE
App Not Running after Installation - Critical Qt

### ISSUE THREAD

**Issue by OscarLimaEcho** [flathub/org.beeref.BeeRef#68]
I'm on Debian 12 and ran:
`flatpak install org.beeref.BeeRef`
`flatpak run org.beeref.BeeRef`
which only results in:
`INFO __main__: Starting BeeRef version 0.3.3`
`INFO __main__: Using settings: /home/{redacted}/.var/app/org.beeref.BeeRef/config/BeeRef/BeeRef.ini`
`INFO __main__: Logging to: /home/{redacted}/.var/app/org.beeref.BeeRef/config/BeeRef/BeeRef.log`
`CRITICAL Qt: Cannot mix incompatible Qt library (6.7.2) with this library (6.7.3)`
after which it exits

**Comment by dginovker** [comment]
Thanks for the report! Looks like it needs a rebuilt (same as !65)

**Comment by dginovker** [comment]
New build works. It will be up on Flathub in a couple of hours
